# Generated by Django 4.1.3 on 2022-11-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BrgyOfficial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=50)),
                ("mname", models.CharField(blank=True, max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("ext_name", models.CharField(blank=True, max_length=5)),
                ("position", models.CharField(max_length=50)),
                ("start_term", models.DateField()),
                ("end_term", models.DateField()),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default="brgy_officials/default.jpg",
                        upload_to="brgy_officials/",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[["ACTIVE", "ACTIVE"], ["INACTIVE", "INACTIVE"]],
                        default="active",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hotline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("phone_no1", models.CharField(default=None, max_length=11)),
                ("phone_no2", models.CharField(blank=True, max_length=11)),
                ("tel_no", models.CharField(blank=True, max_length=15)),
                ("email", models.EmailField(blank=True, max_length=50)),
                ("address", models.CharField(max_length=50)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Purok",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Resident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("mname", models.CharField(blank=True, max_length=50)),
                ("ext_name", models.CharField(blank=True, max_length=5)),
                ("bdate", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[["MALE", "MALE"], ["FEMALE", "FEMALE"]],
                        default="MALE",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
