# Generated by Django 4.1.3 on 2022-11-23 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Blotter",
            fields=[
                ("blotter_no", models.AutoField(primary_key=True, serialize=False)),
                ("incident_type", models.CharField(max_length=50)),
                ("datetimeReported", models.DateTimeField(auto_now_add=True)),
                ("dateOfIncident", models.DateField()),
                ("placeOfIncident", models.CharField(max_length=50)),
                ("hearingDate", models.DateField()),
                ("hearingTime", models.TimeField()),
                ("status", models.CharField(max_length=50)),
                ("narrative", models.TextField()),
                (
                    "recordedBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BrgyOfficial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=50)),
                ("mname", models.CharField(blank=True, max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("ext_name", models.CharField(blank=True, max_length=5)),
                ("position", models.CharField(max_length=50)),
                ("start_term", models.DateField()),
                ("end_term", models.DateField()),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default="brgy_officials/default.jpg",
                        upload_to="brgy_officials/",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[["ACTIVE", "ACTIVE"], ["INACTIVE", "INACTIVE"]],
                        default="active",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BrgyOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("org_name", models.CharField(max_length=50, unique=True)),
                ("org_description", models.CharField(max_length=100)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Hotline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("phone_no1", models.CharField(default=None, max_length=11)),
                ("phone_no2", models.CharField(blank=True, max_length=11)),
                ("tel_no", models.CharField(blank=True, max_length=15)),
                ("email", models.EmailField(blank=True, max_length=50)),
                ("address", models.CharField(max_length=50)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Purok",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Witness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("mname", models.CharField(blank=True, max_length=50)),
                ("ext_name", models.CharField(blank=True, max_length=5)),
                ("contact", models.CharField(max_length=11)),
                ("address", models.CharField(max_length=50)),
                (
                    "blotter_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.blotter"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Respondent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("mname", models.CharField(blank=True, max_length=50)),
                ("ext_name", models.CharField(blank=True, max_length=5)),
                ("contact", models.CharField(max_length=11)),
                ("address", models.CharField(max_length=50)),
                (
                    "blotter_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.blotter"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "res_id",
                    models.CharField(default="MASILI-RES-ID-000000", max_length=50),
                ),
                ("fname", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("mname", models.CharField(blank=True, max_length=50)),
                ("ext_name", models.CharField(blank=True, max_length=5)),
                ("bdate", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[["MALE", "MALE"], ["FEMALE", "FEMALE"]],
                        default="MALE",
                        max_length=10,
                    ),
                ),
                (
                    "civil_status",
                    models.CharField(
                        choices=[
                            ["SINGLE", "SINGLE"],
                            ["MARRIED", "MARRIED"],
                            ["WIDOWED", "WIDOWED"],
                            ["SEPARATED", "SEPARATED"],
                            ["DIVORCED", "DIVORCED"],
                        ],
                        default="SINGLE",
                        max_length=10,
                    ),
                ),
                ("religion", models.CharField(max_length=50)),
                ("occupation", models.CharField(default=None, max_length=50)),
                ("address_line1", models.CharField(default=None, max_length=50)),
                ("phone_no1", models.CharField(default=None, max_length=11)),
                ("phone_no2", models.CharField(blank=True, max_length=11)),
                ("tel_no", models.CharField(blank=True, max_length=15)),
                ("email", models.EmailField(blank=True, max_length=50)),
                ("is_voter", models.BooleanField(default=False)),
                ("is_household_head", models.BooleanField(default=False)),
                (
                    "purok",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.purok",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("mname", models.CharField(blank=True, max_length=50)),
                ("ext_name", models.CharField(blank=True, max_length=5)),
                ("phone_no", models.CharField(default=None, max_length=11)),
                (
                    "res",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.resident"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Complainant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("mname", models.CharField(blank=True, max_length=50)),
                ("ext_name", models.CharField(blank=True, max_length=5)),
                ("contact", models.CharField(max_length=11)),
                ("address", models.CharField(max_length=50)),
                (
                    "blotter_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.blotter"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[["SENT", "SENT"], ["PENDING", "PENDING"]],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrgMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.resident",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.brgyorganization",
                    ),
                ),
            ],
            options={
                "unique_together": {("org", "member")},
            },
        ),
    ]
