# Generated by Django 4.1.3 on 2022-12-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hearing',
            name='time',
        ),
        migrations.AlterField(
            model_name='hearing',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
