# Generated by Django 4.1.3 on 2022-11-21 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blotter",
            fields=[
                ("blotter_no", models.AutoField(primary_key=True, serialize=False)),
                ("incident_type", models.CharField(max_length=50)),
                ("datetimeReported", models.DateTimeField(auto_now_add=True)),
                ("dateOfIncident", models.DateField()),
                ("placeOfIncident", models.CharField(max_length=50)),
                ("hearingDate", models.DateField()),
                ("hearingTime", models.TimeField()),
                ("status", models.CharField(max_length=50)),
                ("narrative", models.TextField()),
                (
                    "recordedBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BrgyOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("org_name", models.CharField(max_length=50)),
                ("org_description", models.CharField(max_length=100)),
                ("org_head", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="resident",
            name="address_line1",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name="resident",
            name="civil_status",
            field=models.CharField(
                choices=[
                    ["SINGLE", "SINGLE"],
                    ["MARRIED", "MARRIED"],
                    ["WIDOWED", "WIDOWED"],
                    ["SEPARATED", "SEPARATED"],
                    ["DIVORCED", "DIVORCED"],
                ],
                default="SINGLE",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="resident",
            name="email",
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="resident",
            name="is_household_head",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resident",
            name="is_voter",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resident",
            name="occupation",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name="resident",
            name="phone_no1",
            field=models.CharField(default=None, max_length=11),
        ),
        migrations.AddField(
            model_name="resident",
            name="phone_no2",
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name="resident",
            name="purok",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.purok",
            ),
        ),
        migrations.AddField(
            model_name="resident",
            name="religion",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resident",
            name="tel_no",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.CreateModel(
            name="Witness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("mname", models.CharField(blank=True, max_length=50)),
                ("ext_name", models.CharField(blank=True, max_length=5)),
                ("contact", models.CharField(max_length=11)),
                ("address", models.CharField(max_length=50)),
                (
                    "blotter_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.blotter"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Respondent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("mname", models.CharField(blank=True, max_length=50)),
                ("ext_name", models.CharField(blank=True, max_length=5)),
                ("contact", models.CharField(max_length=11)),
                ("address", models.CharField(max_length=50)),
                (
                    "blotter_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.blotter"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrgMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("org_member_position", models.CharField(max_length=50)),
                ("org_member_status", models.BooleanField(default=True)),
                (
                    "org_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.brgyorganization",
                    ),
                ),
                (
                    "org_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.resident"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("mname", models.CharField(blank=True, max_length=50)),
                ("ext_name", models.CharField(blank=True, max_length=5)),
                ("phone_no", models.CharField(default=None, max_length=11)),
                (
                    "res",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.resident"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Complainant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("mname", models.CharField(blank=True, max_length=50)),
                ("ext_name", models.CharField(blank=True, max_length=5)),
                ("contact", models.CharField(max_length=11)),
                ("address", models.CharField(max_length=50)),
                (
                    "blotter_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.blotter"
                    ),
                ),
            ],
        ),
    ]
