# Generated by Django 4.1.3 on 2022-12-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationscta',
            name='notification_type',
        ),
    ]
