# Generated by Django 4.1.3 on 2022-11-23 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_gallery"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gallery",
            options={"verbose_name": "Gallery", "verbose_name_plural": "Gallery"},
        ),
    ]
