# Generated by Django 4.1.3 on 2022-12-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_hearing_time_alter_hearing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hearing',
            name='hearing_no',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
