# Generated by Django 4.1.3 on 2022-11-21 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_blotter_brgyorganization_resident_address_line1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brgyorganization",
            name="org_head",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.resident",
            ),
        ),
    ]
