# Generated by Django 4.1.3 on 2022-12-13 02:08

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_notificationscta_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('front_image', models.ImageField(blank=True, default=None, null=True, upload_to=None)),
                ('content', tinymce.models.HTMLField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('posted_by', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
