# Generated by Django 4.1.3 on 2022-11-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_gallery_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="photo",
            field=models.ImageField(upload_to="gallery/"),
        ),
    ]
