# Generated by Django 4.1.3 on 2022-12-15 09:01

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hearing_hearing_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hearing',
            name='remarks',
            field=tinymce.models.HTMLField(),
        ),
    ]
