# Generated by Django 4.1.3 on 2022-12-13 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='front_image',
        ),
    ]
