# Generated by Django 4.1.3 on 2022-12-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_news_front_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='front_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=None),
        ),
    ]
