# Generated by Django 4.1.3 on 2022-12-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_hearing_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hearing',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='blotter_files/'),
        ),
    ]
