# Generated by Django 4.1.3 on 2022-11-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_gallery_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="send_to",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
