# Generated by Django 4.1.3 on 2022-11-21 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_brgyorganization_org_head_delete_orgmember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brgyorganization",
            name="org_head",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.resident",
            ),
        ),
    ]
