# Generated by Django 4.1.3 on 2022-12-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_hearing_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='chairman',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
