# Generated by Django 4.1.3 on 2022-12-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_gallery_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='post_status',
            field=models.CharField(choices=[['PUBLISHED', 'PUBLISHED'], ['DRAFT', 'DRAFT']], default='DRAFT', max_length=50),
        ),
    ]
