# Generated by Django 4.1.3 on 2022-12-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_certificaterequest_chairman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondent',
            name='ext_name',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[['PENDING', 'PENDING'], ['PRINTED', 'PRINTED'], ['ISSUED', 'ISSUED']], default='PENDING', max_length=50),
        ),
    ]
