# Generated by Django 4.1.3 on 2022-12-15 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_respondent_ext_name_alter_certificate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blotter',
            name='recordedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.barangayofficial'),
        ),
    ]
