# Generated by Django 4.1.3 on 2022-12-15 07:18

import apps.authentication.helper
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[['RESIDENT', 'RESIDENT'], ['ADMIN', 'ADMIN'], ['OFFICIAL', 'OFFICIAL'], ['CHAIRMAN', 'CHAIRMAN'], ['SECRETARY', 'SECRETARY']], default='RESIDENT', max_length=20)),
                ('photo', models.ImageField(blank=True, default='profile_pics/default.jpg', storage=apps.authentication.helper.OverwriteStorage(), upload_to=None)),
                ('birthdate', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
