# Generated by Django 4.1.3 on 2022-11-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_guest",
        ),
        migrations.AlterField(
            model_name="profile",
            name="is_resident",
            field=models.BooleanField(default=True),
        ),
    ]
