# Generated by Django 4.1.3 on 2022-11-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_profile_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="accountType",
        ),
        migrations.AddField(
            model_name="profile",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_guest",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_resident",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_superadmin",
            field=models.BooleanField(default=False),
        ),
    ]
