# Generated by Django 4.1.3 on 2022-11-23 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_gallery"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Gallery",
        ),
    ]
